export const initialMusicianList = [
  {
    id: 908234,
    firstName: "Tom",
    lastName: "Dennis",
    instrument: "Trumpet",
    location: "London",
  },
  {
    id: 873648,
    firstName: "Philipa",
    lastName: "Howden",
    instrument: "Piano",
    location: "London",
  },
  {
    id: 676521,
    firstName: "Greg",
    lastName: "Landau",
    instrument: "French Horn",
    location: "Manchester",
  },
  {
    id: 789678,
    firstName: "Rebecca",
    lastName: "Horden",
    instrument: "Drums",
    location: "Glasgow",
  },
  {
    id: 123456,
    firstName: "John",
    lastName: "Smith",
    instrument: "Guitar",
    location: "Edinburgh",
  },
  {
    id: 987654,
    firstName: "Alice",
    lastName: "Jones",
    instrument: "Tenor Sax",
    location: "Birmingham",
  },
  {
    id: 234567,
    firstName: "David",
    lastName: "Brown",
    instrument: "Bass",
    location: "Liverpool",
  },
  {
    id: 345678,
    firstName: "Emma",
    lastName: "Miller",
    instrument: "Alto Sax",
    location: "Cardiff",
  },
  {
    id: 567890,
    firstName: "Michael",
    lastName: "Taylor",
    instrument: "Violin",
    location: "Bristol",
  },
  {
    id: 789012,
    firstName: "Sophie",
    lastName: "Clark",
    instrument: "Clarinet",
    location: "Newcastle",
  },
  {
    id: 654321,
    firstName: "Oliver",
    lastName: "White",
    instrument: "Trombone",
    location: "Leeds",
  },
  {
    id: 901234,
    firstName: "Eleanor",
    lastName: "Lee",
    instrument: "Piano",
    location: "Sheffield",
  },
  {
    id: 876543,
    firstName: "Matthew",
    lastName: "Hill",
    instrument: "Trumpet",
    location: "Nottingham",
  },
  {
    id: 432109,
    firstName: "Laura",
    lastName: "Mason",
    instrument: "Violin",
    location: "Oxford",
  },
  {
    id: 112233,
    firstName: "Daniel",
    lastName: "Woods",
    instrument: "Guitar",
    location: "Cambridge",
  },
  {
    id: 445566,
    firstName: "Grace",
    lastName: "Fisher",
    instrument: "Trumpet",
    location: "Aberdeen",
  },
  {
    id: 778899,
    firstName: "Peter",
    lastName: "Chapman",
    instrument: "Trombone",
    location: "Dundee",
  },
];
